name = "lakeshore-convenience"
compatibility_date = "2025-11-28"
pages_build_output_dir = "./dist"

[vars]
VITE_API_URL = "https://lakeshoreconveniencee-backend-production.up.railway.app"
VITE_FRONTEND_URL = "https://lakeshoreconvenience.com"